server:
  port: 2333
  address: 0.0.0.0
  password: "loc.1005"
  sources:
    youtube: true
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    mixer: true
    http: true
  opus: true
  stats: true
